-- Migration: 010
-- Description: Seed initial NSQF courses data
-- Date: 2026-04-28

INSERT INTO `courses` (`course_name`, `duration`, `eligibility`, `status`) VALUES
('O level (IT)', '540 Hours', 'Level 4 (18 Credits)', 'active'),
('A level', '1620 Hours', 'Level 5 (54 Credits)', 'active'),
('Course on Computer Concepts (CCC)', '80 Hours', 'Level 3 (3 Credits)', 'active'),
('Data Analysis Associate', '450 Hours', 'Level 3 (15 Credits)', 'active'),
('Cyber Security Assistant', '300 Hours', 'Level 3 (10 Credits)', 'active'),
('Junior Cyber Security Associate', '450 Hours', 'Level 4 (15 Credits)', 'active'),
('Cyber Security Associate', '540 Hours', 'Level 4.5 (18 Credits)', 'active'),
('Cloud Computing Assistant', '300 Hours', 'Level 3 (10 Credits)', 'active'),
('Junior Cloud Computing Associate', '450 Hours', 'Level 4 (15 Credits)', 'active'),
('Artificial Intelligence Assistant', '300 Hours', 'Level 3 (10 Credits)', 'active'),
('Artificial Intelligence Associate', '450 Hours', 'Level 4 (15 Credits)', 'active'),
('Artificial Intelligence Application Developer', '540 Hours', 'Level 4.5 (18 Credits)', 'active'),
('Cloud Computing with AWS and Azure', '120 Hours', 'Level 3 (4 Credits)', 'active'),
('Data Analysis with Python and SQL', '120 Hours', 'Level 3 (4 Credits)', 'active'),
('Basics of Python Programming', '30 Hours', 'Level 3 (1 Credit)', 'active'),
('Overview of AI Technology', '7.5 Hours', 'Level 3 (0.25 Credits)', 'active'),
('Overview of Data Science', '7.5 Hours', 'Level 3 (0.25 Credits)', 'active'),
('Scientific Assistant in Data Science for Life Sciences', '450 Hours', 'Level 4 (15 Credits)', 'active'),
('Multimedia Data Analyst', '660 Hours', 'Level 3.5 (22 Credits)', 'active'),
('ITeS BPO Executive - Voice', '330 Hours', 'Level 3 (11 Credits)', 'active'),
('Multimedia Development Associate', '330 Hours', 'Level 3 (11 Credits)', 'active'),
('Cyber Security and Social Media Analyst', '540 Hours', 'Level 3 (18 Credits)', 'active'),
('Full Stack Development Associate', '390 Hours', 'Level 4 (13 Credits)', 'active'),
('Essentials of Data Warehousing', '90 Hours', 'Level 3 (3 Credits)', 'active'),
('Essentials of Big Data', '90 Hours', 'Level 3 (3 Credits)', 'active'),
('Cyber Security for Cloud Infrastructure', '120 Hours', 'Level 3 (4 Credits)', 'active'),
('Vulnerability Assessment and Penetration Testing and IAM Essentials', '90 Hours', 'Level 3 (3 Credits)', 'active'),
('New Technologies Introduction', '60 Hours', 'Level 3 (2 Credits)', 'active'),
('Risk Control and Internal Audit - IT', '60 Hours', 'Level 3 (2 Credits)', 'active'),
('IT Professional Skills', '60 Hours', 'Level 3 (2 Credits)', 'active'),
('Basics of Artificial Intelligence & Data Science', '15 Hours', 'Level 3.5 (0.5 Credits)', 'active'),
('Introduction to Data Annotation', '15 Hours', 'Level 3.5 (0.5 Credits)', 'active'),
('Basics of Text Annotation', '7.5 Hours', 'Level 3.5 (0.25 Credits)', 'active'),
('Basics of Image & Video Annotation', '15 Hours', 'Level 3.5 (0.5 Credits)', 'active'),
('Basics of Audio Annotation', '7.5 Hours', 'Level 3.5 (0.25 Credits)', 'active'),
('Emerging trends in AI Assisted Annotation and Best Practices', '15 Hours', 'Level 3.5 (0.5 Credits)', 'active'),
('Applications of Data Annotation in Agriculture', '30 Hours', 'Level 3.5 (1 Credit)', 'active'),
('Applications of Data Annotation in Education', '30 Hours', 'Level 3.5 (1 Credit)', 'active'),
('Applications of Data Annotation in Healthcare', '30 Hours', 'Level 3.5 (1 Credit)', 'active'),
('Applications of Data Annotation in Manufacturing', '30 Hours', 'Level 3.5 (1 Credit)', 'active'),
('Introduction to Data Curation', '7.5 Hours', 'Level 3.5 (0.25 Credits)', 'active'),
('Introduction to Data Collection & Acquisition Methods', '22.5 Hours', 'Level 3.5 (0.75 Credits)', 'active');
